---
title: "Chaper 2 Exercises"
author: "Jonathan Bryan"
date: "May 7, 2017"
output: html_document
---

### 1. For each of parts (a) through (d), indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.

#### (a) The sample size n is extremely large, and the number of predictors p is small.
Flexible models perform well when the sample size of the training set is large and a large number of parameters can be estimated to build the flexible model. Therefore a flexible model may be preferred.

#### (b) The number of predictors p is extremely large, and the number of observations n is small.
Flexible models can be difficult or impossible to fit when there are not enough observations available. A flexible model may also over fit the small number of observation, performing poorly on out-of-sample testing. Therefore a flexible model may not be preferred.

#### (C) The relationship between the predictors and response is highly non-linear.
Many flexible models can more easily and accurately model non-linear behavior so a non-linear model may be preferred.

#### (d) The variance of the error terms, i.e. $σ_2 = Var(\epsilon)$, is extremely high.
Flexible models tend to "chase" or closely follow the variation found in the training set data. This leads to high variability each time the model is run on different sets of training data. Therefore, increasing the variability of the noise in the data will increase the variability in the flexible model which is sub optimal. Therefore, a more flexible model may not be preferred.

### Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide n and p.

#### (a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.
This is a regression problem with the goal of inference (n = 500 and p = 4).


#### (b) We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.
This is a classification problem with the goal of prediction (n = 20 and p = 13).


#### (c) We are interesting in predicting the % change in the US dollar in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the dollar, the % change in the US market, the % change in the British market, and the % change in the German market.
This is a regression problem with the goal of prediction (n = 366 and p = 3).

### We now revisit the bias-variance decomposition. 

#### (a) Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods towards more flexible approaches. The x-axis should represent the amount of flexibility in the method, and the y-axis should represent the values for each curve. There should be five curves. Make sure to label each one.
```{r}



```









