---
title: 'Lab 2: Clustering'
author: "Jonathan Bryan"
date: "August 31, 2018"
output: pdf_document
---
```{r echo = FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=5) 
```

### 10.5.1 K-Means Clustering

```{r}
#simulated data generation
set.seed(2)
x = matrix(rnorm(50*2), ncol = 2)
x[1:25,1] = x[1:25,1]+3
x[1:25,2] = x[1:25,2]-4
```

```{r}
#k-means clustering
km.out = kmeans(x,2,nstart = 20)
km.out$cluster
```

```{r}
#plot k=2 cluster
plot(x, col = (km.out$cluster + 1),
     main = "K-Means Clustering Results with K=2",
     xlab = "",
     ylab ="",
     pch = 20,
     cex = 2)
```

```{r}
#k=3 clustering
set.seed(4)
km.out = kmeans(x, 3, nstart = 20)
km.out
```

```{r}
#nstart controls number of k-means run
set.seed(3)
km.out = kmeans(x,3,nstart = 1)
km.out$tot.withinss
```

```{r}
km.out = kmeans(x,3,nstart=20)
km.out$tot.withinss
```

### 10.5.2 Hierarchical Clustering

```{r}
hc.complete = hclust(dist(x), method = "complete")
hc.average = hclust(dist(x), method = "average")
hc.single = hclust(dist(x), method = "single")
```

```{r}
par(mfrow = c(1,3))
plot(hc.complete,
     main = "Complete Linkage",
     xlab = "",
     sub = "",
     cex = 0.9)
plot(hc.average,
     main = "Average Linkage",
     xlab = "",
     sub = "",
     cex = 0.9)
plot(hc.single,
     main = "Single Linkage",
     xlab = "",
     sub = "",
     cex = 0.9)
```

```{r}
cutree(hc.complete, 2)
cutree(hc.average, 2)
cutree(hc.single, 2)
cutree(hc.single, 4)
```

```{r}
xsc = scale(x)
plot(hclust(dist(xsc),
            method = "complete"),
     main = "Hierarchical Clustering with Scaled Features")
```

```{r}
#correlation-based distance requires at least 3 features
x = matrix(rnorm(30*3), ncol = 3)
dd = as.dist(1 - cor(t(x)))
plot(hclust(dd, method = "complete"), main = "Complete Linkage with Correlation-Based Distance", xlab ="", sub = "")
```