---
title: 'Lab 3: NCI60 Data Example'
author: "Jonathan Bryan"
date: "August 31, 2018"
output: pdf_document
---
```{r echo = FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=5) 
```

```{r}
library(ISLR)
nci.labs = NCI60$labs
nci.data = NCI60$data
dim(nci.data)
nci.labs[1:4]
table(nci.labs)
```

### 10.6.1 PCA on the NCI60 Data

```{r}
#PCA
pr.out = prcomp(nci.data, scale = TRUE)

#assign colors to cell lines
Cols = function(vec){
  cols = rainbow(length(unique(vec)))
  return(cols[as.numeric(as.factor(vec))])
}
```

```{r}
par(mfrow=c(1,2))
plot(pr.out$x[,1:2],
     col = Cols(nci.labs),
     pch = 19,
     xlab = "Z1",
     ylab = "Z2")
plot(pr.out$x[,c(1,3)],
     col = Cols(nci.labs),
     pch = 19,
     xlab = "Z1",
     ylab = "Z3")
```

```{r}
summary(pr.out)
```

```{r}
#plot variance explained by first few principal components
plot(pr.out)
```

```{r}
pve = 100*pr.out$sdev^2/sum(pr.out$sdev^2)
par(mfrow = c(1,2))
plot(pve, 
     type = "o",
     ylab = "PVE",
     xlab = "Principal Component",
     col = "blue")
plot(cumsum(pve),
     type = "o",
     ylab = "Cumulative PVE",
     xlab = "Principal Component",
     col = "brown3")
```

### 10.6.2 Clustering the Observations of the NCI60 Data

```{r}
sd.data = scale(nci.data)
par(mfrow = c(1,3))
data.dist = dist(sd.data)
plot(hclust(data.dist, method = "complete"),
     labels = nci.labs,
     main = "Complete Linkage",
     xlab = "",
     sub = "",
     ylab = "")
plot(hclust(data.dist, method = "average"),
     labels = nci.labs,
     main = "Average Linkage",
     xlab = "",
     sub = "",
     ylab = "")
plot(hclust(data.dist, method = "single"),
     labels = nci.labs,
     main = "Single Linkage",
     xlab = "",
     sub = "",
     ylab = "")
```

```{r}
#proceed with complete linkage and cut at height to yield 4 clusters
hc.out = hclust(dist(sd.data))
hc.clusters = cutree(hc.out,4)
table(hc.clusters, nci.labs)
```

```{r}
par(mfrow = c(1,1))
plot(hc.out, labels = nci.labs)
abline(h=139, col="red")
```

```{r}
hc.out
```

```{r}
# k=4 clustering compared to hierarchical clustering
set.seed(2)
km.out = kmeans(sd.data, 4, nstart = 20)
km.clusters = km.out$cluster
table(km.clusters, hc.clusters)
```

```{r}
#hierarchical clustering on first few principal compoenents
hc.out = hclust(dist(pr.out$x[,1:5]))
plot(hc.out, labels = nci.labs, main = "Hier. Clust. on First Five Score Vectors")
table(cutree(hc.out,4), nci.labs)
```



